[versions]
jetbrains-annotations = "26.0.2-1"
graal-collections = "25.0.0"
lwjgl = "3.4.0"
slf4j = "2.0.17"
log4j = "2.25.3"
fastutil = "8.5.18"
jolt = "3.5.2"
snaploader = "1.1.1-stable"
oshi = "6.9.2"
gson = "2.13.2"
dfu = "9.0.19"

[libraries]
lwjgl-bom = { group = "org.lwjgl", name = "lwjgl-bom", version.ref = "lwjgl" }

lwjgl = { group = "org.lwjgl", name = "lwjgl" }
lwjgl-assimp = { group = "org.lwjgl", name = "lwjgl-assimp" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw" }
lwjgl-meshoptimizer = { group = "org.lwjgl", name = "lwjgl-meshoptimizer" }
lwjgl-msdfgen = { group = "org.lwjgl", name = "lwjgl-msdfgen" }
lwjgl-stb = { group = "org.lwjgl", name = "lwjgl-stb" }
lwjgl-vma = { group = "org.lwjgl", name = "lwjgl-vma" }
lwjgl-vulkan = { group = "org.lwjgl", name = "lwjgl-vulkan" }

graal-collections = { module = "org.graalvm.sdk:collections", version.ref = "graal-collections" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }

jolt = { module = "com.github.stephengold:jolt-jni-Windows64", version.ref = "jolt" }
jolt-windows = { module = "com.github.stephengold:jolt-jni-Windows64", version.ref = "jolt" }
jolt-linux = { module = "com.github.stephengold:jolt-jni-Linux64", version.ref = "jolt" }
jolt-mac = { module = "com.github.stephengold:jolt-jni-MacOSX64", version.ref = "jolt" }

snaploader = { module = "io.github.electrostat-lab:snaploader", version.ref = "snaploader" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
datafixerupper = { group = "com.mojang", name = "datafixerupper", version.ref = "dfu" }

[bundles]
snaploader = [ "snaploader", "oshi-core" ]