package net.flamgop.borked.engine.memory;

import static org.lwjgl.vulkan.AMDXShaderEnqueue.VK_BUFFER_USAGE_EXECUTION_GRAPH_SCRATCH_BIT_AMDX;
import static org.lwjgl.vulkan.EXTConditionalRendering.VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT;
import static org.lwjgl.vulkan.EXTDescriptorBuffer.*;
import static org.lwjgl.vulkan.EXTTransformFeedback.VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT;
import static org.lwjgl.vulkan.EXTTransformFeedback.VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT;
import static org.lwjgl.vulkan.KHRAccelerationStructure.VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR;
import static org.lwjgl.vulkan.KHRAccelerationStructure.VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR;
import static org.lwjgl.vulkan.KHRRayTracingPipeline.VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoDecodeQueue.VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoDecodeQueue.VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR;
import static org.lwjgl.vulkan.KHRVideoEncodeQueue.VK_BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR;
import static org.lwjgl.vulkan.NVRayTracing.VK_BUFFER_USAGE_RAY_TRACING_BIT_NV;
import static org.lwjgl.vulkan.VK14.*;

public class BufferUsage {
    public static final int TRANSFER_SRC_BIT = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
    public static final int TRANSFER_DST_BIT = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    public static final int UNIFORM_TEXEL_BUFFER_BIT = VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT;
    public static final int STORAGE_TEXEL_BUFFER_BIT = VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT;
    public static final int UNIFORM_BUFFER_BIT = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;
    public static final int STORAGE_BUFFER_BIT = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    public static final int INDEX_BUFFER_BIT = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
    public static final int VERTEX_BUFFER_BIT = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    public static final int INDIRECT_BUFFER_BIT = VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT;

    public static final int CONDITIONAL_RENDERING_BIT_EXT = VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT;
    public static final int TRANSFORM_FEEDBACK_BUFFER_BIT_EXT = VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT;
    public static final int TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT = VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT;
    public static final int SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT = VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT;
    public static final int RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT = VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT;
    public static final int PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT = VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT;
    public static final int RAY_TRACING_BIT_NV = VK_BUFFER_USAGE_RAY_TRACING_BIT_NV;
    public static final int SHADER_BINDING_TABLE_BIT_KHR = VK_BUFFER_USAGE_SHADER_BINDING_TABLE_BIT_KHR;
    public static final int ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR = VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR;
    public static final int ACCELERATION_STRUCTURE_STORAGE_BIT_KHR = VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR;
    public static final int SHADER_DEVICE_ADDRESS_BIT = VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
    public static final int VIDEO_DECODE_SRC_BIT_KHR = VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR;
    public static final int VIDEO_DECODE_DST_BIT_KHR = VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR;
    public static final int VIDEO_ENCODE_DST_BIT_KHR = VK_BUFFER_USAGE_VIDEO_ENCODE_DST_BIT_KHR;
    public static final int EXECUTION_GRAPH_SCRATCH_BIT_AMDX = VK_BUFFER_USAGE_EXECUTION_GRAPH_SCRATCH_BIT_AMDX;
}
